/* Auto-generated by genmsg_cpp for file /home/vektor/hiroken-ros-pkg/nn_machine/srv/TrainNet.srv */
#ifndef NN_MACHINE_SERVICE_TRAINNET_H
#define NN_MACHINE_SERVICE_TRAINNET_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace nn_machine
{
template <class ContainerAllocator>
struct TrainNetRequest_ {
  typedef TrainNetRequest_<ContainerAllocator> Type;

  TrainNetRequest_()
  {
  }

  TrainNetRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::nn_machine::TrainNetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nn_machine::TrainNetRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TrainNetRequest
typedef  ::nn_machine::TrainNetRequest_<std::allocator<void> > TrainNetRequest;

typedef boost::shared_ptr< ::nn_machine::TrainNetRequest> TrainNetRequestPtr;
typedef boost::shared_ptr< ::nn_machine::TrainNetRequest const> TrainNetRequestConstPtr;


template <class ContainerAllocator>
struct TrainNetResponse_ {
  typedef TrainNetResponse_<ContainerAllocator> Type;

  TrainNetResponse_()
  : msg()
  {
  }

  TrainNetResponse_(const ContainerAllocator& _alloc)
  : msg(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::nn_machine::TrainNetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nn_machine::TrainNetResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TrainNetResponse
typedef  ::nn_machine::TrainNetResponse_<std::allocator<void> > TrainNetResponse;

typedef boost::shared_ptr< ::nn_machine::TrainNetResponse> TrainNetResponsePtr;
typedef boost::shared_ptr< ::nn_machine::TrainNetResponse const> TrainNetResponseConstPtr;

struct TrainNet
{

typedef TrainNetRequest Request;
typedef TrainNetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct TrainNet
} // namespace nn_machine

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nn_machine::TrainNetRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nn_machine::TrainNetRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nn_machine::TrainNetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::nn_machine::TrainNetRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::nn_machine::TrainNetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nn_machine/TrainNetRequest";
  }

  static const char* value(const  ::nn_machine::TrainNetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nn_machine::TrainNetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::nn_machine::TrainNetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nn_machine::TrainNetRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nn_machine::TrainNetResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nn_machine::TrainNetResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nn_machine::TrainNetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const  ::nn_machine::TrainNetResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7d96ed7307768047ULL;
  static const uint64_t static_value2 = 0x54140b85e64c862eULL;
};

template<class ContainerAllocator>
struct DataType< ::nn_machine::TrainNetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nn_machine/TrainNetResponse";
  }

  static const char* value(const  ::nn_machine::TrainNetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nn_machine::TrainNetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::nn_machine::TrainNetResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nn_machine::TrainNetRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TrainNetRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nn_machine::TrainNetResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TrainNetResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<nn_machine::TrainNet> {
  static const char* value() 
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const nn_machine::TrainNet&) { return value(); } 
};

template<>
struct DataType<nn_machine::TrainNet> {
  static const char* value() 
  {
    return "nn_machine/TrainNet";
  }

  static const char* value(const nn_machine::TrainNet&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<nn_machine::TrainNetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const nn_machine::TrainNetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<nn_machine::TrainNetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nn_machine/TrainNet";
  }

  static const char* value(const nn_machine::TrainNetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<nn_machine::TrainNetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const nn_machine::TrainNetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<nn_machine::TrainNetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nn_machine/TrainNet";
  }

  static const char* value(const nn_machine::TrainNetResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NN_MACHINE_SERVICE_TRAINNET_H

