/* Auto-generated by genmsg_cpp for file /home/vektor/4/ros-pkg/hiro_control/srv/CommitMovingArm.srv */
#ifndef HIRO_CONTROL_SERVICE_COMMITMOVINGARM_H
#define HIRO_CONTROL_SERVICE_COMMITMOVINGARM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hiro_control
{
template <class ContainerAllocator>
struct CommitMovingArmRequest_ {
  typedef CommitMovingArmRequest_<ContainerAllocator> Type;

  CommitMovingArmRequest_()
  : signal(0)
  {
  }

  CommitMovingArmRequest_(const ContainerAllocator& _alloc)
  : signal(0)
  {
  }

  typedef uint8_t _signal_type;
  uint8_t signal;


  typedef boost::shared_ptr< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CommitMovingArmRequest
typedef  ::hiro_control::CommitMovingArmRequest_<std::allocator<void> > CommitMovingArmRequest;

typedef boost::shared_ptr< ::hiro_control::CommitMovingArmRequest> CommitMovingArmRequestPtr;
typedef boost::shared_ptr< ::hiro_control::CommitMovingArmRequest const> CommitMovingArmRequestConstPtr;


template <class ContainerAllocator>
struct CommitMovingArmResponse_ {
  typedef CommitMovingArmResponse_<ContainerAllocator> Type;

  CommitMovingArmResponse_()
  : msg()
  {
  }

  CommitMovingArmResponse_(const ContainerAllocator& _alloc)
  : msg(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CommitMovingArmResponse
typedef  ::hiro_control::CommitMovingArmResponse_<std::allocator<void> > CommitMovingArmResponse;

typedef boost::shared_ptr< ::hiro_control::CommitMovingArmResponse> CommitMovingArmResponsePtr;
typedef boost::shared_ptr< ::hiro_control::CommitMovingArmResponse const> CommitMovingArmResponseConstPtr;

struct CommitMovingArm
{

typedef CommitMovingArmRequest Request;
typedef CommitMovingArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CommitMovingArm
} // namespace hiro_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6ce8cf9f366ca33ffbb7008845f62def";
  }

  static const char* value(const  ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6ce8cf9f366ca33fULL;
  static const uint64_t static_value2 = 0xfbb7008845f62defULL;
};

template<class ContainerAllocator>
struct DataType< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hiro_control/CommitMovingArmRequest";
  }

  static const char* value(const  ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 signal\n\
\n\
";
  }

  static const char* value(const  ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const  ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7d96ed7307768047ULL;
  static const uint64_t static_value2 = 0x54140b85e64c862eULL;
};

template<class ContainerAllocator>
struct DataType< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hiro_control/CommitMovingArmResponse";
  }

  static const char* value(const  ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hiro_control::CommitMovingArmRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.signal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CommitMovingArmRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hiro_control::CommitMovingArmResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CommitMovingArmResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hiro_control::CommitMovingArm> {
  static const char* value() 
  {
    return "8b0c8c802c21c92bce78aaf2cfb5bdb6";
  }

  static const char* value(const hiro_control::CommitMovingArm&) { return value(); } 
};

template<>
struct DataType<hiro_control::CommitMovingArm> {
  static const char* value() 
  {
    return "hiro_control/CommitMovingArm";
  }

  static const char* value(const hiro_control::CommitMovingArm&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hiro_control::CommitMovingArmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8b0c8c802c21c92bce78aaf2cfb5bdb6";
  }

  static const char* value(const hiro_control::CommitMovingArmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hiro_control::CommitMovingArmRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hiro_control/CommitMovingArm";
  }

  static const char* value(const hiro_control::CommitMovingArmRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hiro_control::CommitMovingArmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8b0c8c802c21c92bce78aaf2cfb5bdb6";
  }

  static const char* value(const hiro_control::CommitMovingArmResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hiro_control::CommitMovingArmResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hiro_control/CommitMovingArm";
  }

  static const char* value(const hiro_control::CommitMovingArmResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HIRO_CONTROL_SERVICE_COMMITMOVINGARM_H

