(cl:defpackage learning_machine-srv
  (:use )
  (:export
   "CREATEMETADATA"
   "<CREATEMETADATA-REQUEST>"
   "CREATEMETADATA-REQUEST"
   "<CREATEMETADATA-RESPONSE>"
   "CREATEMETADATA-RESPONSE"
   "TEST"
   "<TEST-REQUEST>"
   "TEST-REQUEST"
   "<TEST-RESPONSE>"
   "TEST-RESPONSE"
   "TRAIN"
   "<TRAIN-REQUEST>"
   "TRAIN-REQUEST"
   "<TRAIN-RESPONSE>"
   "TRAIN-RESPONSE"
  ))

