(cl:defpackage hiro_common-srv
  (:use )
  (:export
   "GETMANIPULABILITY"
   "<GETMANIPULABILITY-REQUEST>"
   "GETMANIPULABILITY-REQUEST"
   "<GETMANIPULABILITY-RESPONSE>"
   "GETMANIPULABILITY-RESPONSE"
   "BENCHMARKPATH"
   "<BENCHMARKPATH-REQUEST>"
   "BENCHMARKPATH-REQUEST"
   "<BENCHMARKPATH-RESPONSE>"
   "BENCHMARKPATH-RESPONSE"
  ))

