// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "safetyPlugin.hpp"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



const char * safetyPlugin::versionStringIDL = "37:238f668b1631";

const char * safetyPlugin::versionDateIDL = "Sat Jan 24 22:38:22 2009 +0900";

safetyPlugin_ptr safetyPlugin_Helper::_nil() {
  return ::safetyPlugin::_nil();
}

::CORBA::Boolean safetyPlugin_Helper::is_nil(::safetyPlugin_ptr p) {
  return ::CORBA::is_nil(p);

}

void safetyPlugin_Helper::release(::safetyPlugin_ptr p) {
  ::CORBA::release(p);
}

void safetyPlugin_Helper::marshalObjRef(::safetyPlugin_ptr obj, cdrStream& s) {
  ::safetyPlugin::_marshalObjRef(obj, s);
}

safetyPlugin_ptr safetyPlugin_Helper::unmarshalObjRef(cdrStream& s) {
  return ::safetyPlugin::_unmarshalObjRef(s);
}

void safetyPlugin_Helper::duplicate(::safetyPlugin_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

safetyPlugin_ptr
safetyPlugin::_duplicate(::safetyPlugin_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

safetyPlugin_ptr
safetyPlugin::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


safetyPlugin_ptr
safetyPlugin::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

safetyPlugin_ptr
safetyPlugin::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_safetyPlugin _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_safetyPlugin* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_safetyPlugin;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* safetyPlugin::_PD_repoId = "IDL:safetyPlugin:1.0";


typedef OpenHRP::Plugin OpenHRP_Plugin;
typedef OpenHRP::_impl_Plugin OpenHRP__impl_Plugin;
typedef OpenHRP::_objref_Plugin OpenHRP__objref_Plugin;

typedef OpenHRP::CommandReceiver OpenHRP_CommandReceiver;
typedef OpenHRP::_impl_CommandReceiver OpenHRP__impl_CommandReceiver;
typedef OpenHRP::_objref_CommandReceiver OpenHRP__objref_CommandReceiver;

_objref_safetyPlugin::~_objref_safetyPlugin() {
  
}


_objref_safetyPlugin::_objref_safetyPlugin(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::safetyPlugin::_PD_repoId, ior, id, 1),
   OpenHRP__objref_Plugin(ior, id)
   
{
  _PR_setobj(this);
}

void*
_objref_safetyPlugin::_ptrToObjRef(const char* id)
{
  if( id == ::safetyPlugin::_PD_repoId )
    return (::safetyPlugin_ptr) this;
  if( id == ::OpenHRP::Plugin::_PD_repoId )
    return (::OpenHRP::Plugin_ptr) this;

  if( id == ::OpenHRP::CommandReceiver::_PD_repoId )
    return (::OpenHRP::CommandReceiver_ptr) this;


  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::safetyPlugin::_PD_repoId) )
    return (::safetyPlugin_ptr) this;
  if( omni::strMatch(id, ::OpenHRP::Plugin::_PD_repoId) )
    return (::OpenHRP::Plugin_ptr) this;

  if( omni::strMatch(id, ::OpenHRP::CommandReceiver::_PD_repoId) )
    return (::OpenHRP::CommandReceiver_ptr) this;


  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _clong_i_cboolean_i_clong
class _0RL_cd_17592487aa922463_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Boolean arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_17592487aa922463_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalBoolean(arg_0);
  arg_1 >>= _n;

}

void _0RL_cd_17592487aa922463_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0 = _n.unmarshalBoolean();
  (::CORBA::Long&)arg_1 <<= _n;

}

void _0RL_cd_17592487aa922463_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_17592487aa922463_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_17592487aa922463_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_00000000* tcd = (_0RL_cd_17592487aa922463_00000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->setAutoSetting(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long _objref_safetyPlugin::setAutoSetting(::CORBA::Boolean reLock, ::CORBA::Long unLockTime)
{
  _0RL_cd_17592487aa922463_00000000 _call_desc(_0RL_lcfn_17592487aa922463_10000000, "setAutoSetting", 15);
  _call_desc.arg_0 = reLock;
  _call_desc.arg_1 = unLockTime;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _clong_o_cboolean_o_clong
class _0RL_cd_17592487aa922463_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Boolean arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_17592487aa922463_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  _n.marshalBoolean(arg_0);
  arg_1 >>= _n;

}

void _0RL_cd_17592487aa922463_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;
  arg_0 = _n.unmarshalBoolean();
  (::CORBA::Long&)arg_1 <<= _n;

}

const char* const _0RL_cd_17592487aa922463_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_20000000* tcd = (_0RL_cd_17592487aa922463_20000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->getAutoSetting(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long _objref_safetyPlugin::getAutoSetting(::CORBA::Boolean& reLock, ::CORBA::Long& unLockTime)
{
  _0RL_cd_17592487aa922463_20000000 _call_desc(_0RL_lcfn_17592487aa922463_30000000, "getAutoSetting", 15);


  _invoke(_call_desc);
  reLock = _call_desc.arg_0;
  unLockTime = _call_desc.arg_1;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _csafetyPlugin_msafetyModuleState
class _0RL_cd_17592487aa922463_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  safetyPlugin::safetyModuleState result;
};

void _0RL_cd_17592487aa922463_40000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_17592487aa922463_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  (safetyPlugin::safetyModuleState&)result <<= _n;

}

const char* const _0RL_cd_17592487aa922463_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transitionP2M();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transitionP2M()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_50000000, "transitionP2M", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transitionM2P();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transitionM2P()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_60000000, "transitionM2P", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transitionP2A();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transitionP2A()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_70000000, "transitionP2A", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transitionA2P();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transitionA2P()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_80000000, "transitionA2P", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transitionA2M();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transitionA2M()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_90000000, "transitionA2M", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transition2E();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transition2E()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_a0000000, "transition2E", 13);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->transitionE2W();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::transitionE2W()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_b0000000, "transitionE2W", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_40000000* tcd = (_0RL_cd_17592487aa922463_40000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->queryState();


}

safetyPlugin::safetyModuleState _objref_safetyPlugin::queryState()
{
  _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_c0000000, "queryState", 11);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong
class _0RL_cd_17592487aa922463_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_d0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::ULong result;
};

void _0RL_cd_17592487aa922463_d0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_17592487aa922463_d0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::ULong&)result <<= _n;

}

const char* const _0RL_cd_17592487aa922463_d0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_d0000000* tcd = (_0RL_cd_17592487aa922463_d0000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->queryWatchDogUpdate();


}

::CORBA::ULong _objref_safetyPlugin::queryWatchDogUpdate()
{
  _0RL_cd_17592487aa922463_d0000000 _call_desc(_0RL_lcfn_17592487aa922463_e0000000, "queryWatchDogUpdate", 20);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _clong_i_cshort_i_clong
class _0RL_cd_17592487aa922463_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_f0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_17592487aa922463_f0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_17592487aa922463_f0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

void _0RL_cd_17592487aa922463_f0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_17592487aa922463_f0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_17592487aa922463_f0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_f0000000* tcd = (_0RL_cd_17592487aa922463_f0000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->setValue(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long _objref_safetyPlugin::setValue(::CORBA::Short id, ::CORBA::Long value)
{
  _0RL_cd_17592487aa922463_f0000000 _call_desc(_0RL_lcfn_17592487aa922463_01000000, "setValue", 9);
  _call_desc.arg_0 = id;
  _call_desc.arg_1 = value;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _clong_i_cshort_o_clong
class _0RL_cd_17592487aa922463_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_11000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_17592487aa922463_11000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_17592487aa922463_11000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_17592487aa922463_11000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_17592487aa922463_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

const char* const _0RL_cd_17592487aa922463_11000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_11000000* tcd = (_0RL_cd_17592487aa922463_11000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->getValue(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long _objref_safetyPlugin::getValue(::CORBA::Short id, ::CORBA::Long& value)
{
  _0RL_cd_17592487aa922463_11000000 _call_desc(_0RL_lcfn_17592487aa922463_21000000, "getValue", 9);
  _call_desc.arg_0 = id;

  _invoke(_call_desc);
  value = _call_desc.arg_1;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plonglong
class _0RL_cd_17592487aa922463_31000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_17592487aa922463_31000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::ULongLong result;
};

void _0RL_cd_17592487aa922463_31000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_17592487aa922463_31000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::ULongLong&)result <<= _n;

}

const char* const _0RL_cd_17592487aa922463_31000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_31000000* tcd = (_0RL_cd_17592487aa922463_31000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->getShmFrameNumber();


}

::CORBA::ULongLong _objref_safetyPlugin::getShmFrameNumber()
{
  _0RL_cd_17592487aa922463_31000000 _call_desc(_0RL_lcfn_17592487aa922463_41000000, "getShmFrameNumber", 18);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_17592487aa922463_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_17592487aa922463_31000000* tcd = (_0RL_cd_17592487aa922463_31000000*)cd;
  _impl_safetyPlugin* impl = (_impl_safetyPlugin*) svnt->_ptrToInterface(safetyPlugin::_PD_repoId);
  tcd->result = impl->getDi();


}

::CORBA::ULongLong _objref_safetyPlugin::getDi()
{
  _0RL_cd_17592487aa922463_31000000 _call_desc(_0RL_lcfn_17592487aa922463_51000000, "getDi", 6);


  _invoke(_call_desc);
  return _call_desc.result;


}
_pof_safetyPlugin::~_pof_safetyPlugin() {}


omniObjRef*
_pof_safetyPlugin::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_safetyPlugin(ior, id);
}


::CORBA::Boolean
_pof_safetyPlugin::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::safetyPlugin::_PD_repoId) )
    return 1;
  if( omni::ptrStrMatch(id, OpenHRP::Plugin::_PD_repoId) )
    return 1;

  if( omni::ptrStrMatch(id, OpenHRP::CommandReceiver::_PD_repoId) )
    return 1;


  return 0;
}

const _pof_safetyPlugin _the_pof_safetyPlugin;

_impl_safetyPlugin::~_impl_safetyPlugin() {}


::CORBA::Boolean
_impl_safetyPlugin::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "setAutoSetting") ) {

    _0RL_cd_17592487aa922463_00000000 _call_desc(_0RL_lcfn_17592487aa922463_10000000, "setAutoSetting", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getAutoSetting") ) {

    _0RL_cd_17592487aa922463_20000000 _call_desc(_0RL_lcfn_17592487aa922463_30000000, "getAutoSetting", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transitionP2M") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_50000000, "transitionP2M", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transitionM2P") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_60000000, "transitionM2P", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transitionP2A") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_70000000, "transitionP2A", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transitionA2P") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_80000000, "transitionA2P", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transitionA2M") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_90000000, "transitionA2M", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transition2E") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_a0000000, "transition2E", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "transitionE2W") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_b0000000, "transitionE2W", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "queryState") ) {

    _0RL_cd_17592487aa922463_40000000 _call_desc(_0RL_lcfn_17592487aa922463_c0000000, "queryState", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "queryWatchDogUpdate") ) {

    _0RL_cd_17592487aa922463_d0000000 _call_desc(_0RL_lcfn_17592487aa922463_e0000000, "queryWatchDogUpdate", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setValue") ) {

    _0RL_cd_17592487aa922463_f0000000 _call_desc(_0RL_lcfn_17592487aa922463_01000000, "setValue", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getValue") ) {

    _0RL_cd_17592487aa922463_11000000 _call_desc(_0RL_lcfn_17592487aa922463_21000000, "getValue", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getShmFrameNumber") ) {

    _0RL_cd_17592487aa922463_31000000 _call_desc(_0RL_lcfn_17592487aa922463_41000000, "getShmFrameNumber", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getDi") ) {

    _0RL_cd_17592487aa922463_31000000 _call_desc(_0RL_lcfn_17592487aa922463_51000000, "getDi", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  
#ifndef _MSC_VER
  if( OpenHRP__impl_Plugin::_dispatch(_handle) ) {
    return 1;
  }
#else
  // Work-around for incorrect MSVC code generation.
  if( ((OpenHRP__impl_Plugin*)this)->
      OpenHRP__impl_Plugin::_dispatch(_handle) ) {
    return 1;
  }
#endif


  return 0;
}

void*
_impl_safetyPlugin::_ptrToInterface(const char* id)
{
  if( id == ::safetyPlugin::_PD_repoId )
    return (::_impl_safetyPlugin*) this;
  if( id == ::OpenHRP::Plugin::_PD_repoId )
    return (::OpenHRP::_impl_Plugin*) this;

  if( id == ::OpenHRP::CommandReceiver::_PD_repoId )
    return (::OpenHRP::_impl_CommandReceiver*) this;


  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::safetyPlugin::_PD_repoId) )
    return (::_impl_safetyPlugin*) this;
  if( omni::strMatch(id, ::OpenHRP::Plugin::_PD_repoId) )
    return (::OpenHRP::_impl_Plugin*) this;

  if( omni::strMatch(id, ::OpenHRP::CommandReceiver::_PD_repoId) )
    return (::OpenHRP::_impl_CommandReceiver*) this;


  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_safetyPlugin::_mostDerivedRepoId()
{
  return ::safetyPlugin::_PD_repoId;
}

POA_safetyPlugin::~POA_safetyPlugin() {}

