/* Auto-generated by genmsg_cpp for file /home/vektor/hiroken-ros-pkg/action_manager/srv/Go2Home.srv */
#ifndef ACTION_MANAGER_SERVICE_GO2HOME_H
#define ACTION_MANAGER_SERVICE_GO2HOME_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace action_manager
{
template <class ContainerAllocator>
struct Go2HomeRequest_ {
  typedef Go2HomeRequest_<ContainerAllocator> Type;

  Go2HomeRequest_()
  {
  }

  Go2HomeRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::action_manager::Go2HomeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_manager::Go2HomeRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Go2HomeRequest
typedef  ::action_manager::Go2HomeRequest_<std::allocator<void> > Go2HomeRequest;

typedef boost::shared_ptr< ::action_manager::Go2HomeRequest> Go2HomeRequestPtr;
typedef boost::shared_ptr< ::action_manager::Go2HomeRequest const> Go2HomeRequestConstPtr;


template <class ContainerAllocator>
struct Go2HomeResponse_ {
  typedef Go2HomeResponse_<ContainerAllocator> Type;

  Go2HomeResponse_()
  {
  }

  Go2HomeResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::action_manager::Go2HomeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_manager::Go2HomeResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Go2HomeResponse
typedef  ::action_manager::Go2HomeResponse_<std::allocator<void> > Go2HomeResponse;

typedef boost::shared_ptr< ::action_manager::Go2HomeResponse> Go2HomeResponsePtr;
typedef boost::shared_ptr< ::action_manager::Go2HomeResponse const> Go2HomeResponseConstPtr;

struct Go2Home
{

typedef Go2HomeRequest Request;
typedef Go2HomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Go2Home
} // namespace action_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::action_manager::Go2HomeRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::action_manager::Go2HomeRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::action_manager::Go2HomeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::action_manager::Go2HomeRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::action_manager::Go2HomeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_manager/Go2HomeRequest";
  }

  static const char* value(const  ::action_manager::Go2HomeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::action_manager::Go2HomeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::action_manager::Go2HomeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::action_manager::Go2HomeRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::action_manager::Go2HomeResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::action_manager::Go2HomeResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::action_manager::Go2HomeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::action_manager::Go2HomeResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::action_manager::Go2HomeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_manager/Go2HomeResponse";
  }

  static const char* value(const  ::action_manager::Go2HomeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::action_manager::Go2HomeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::action_manager::Go2HomeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::action_manager::Go2HomeResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::action_manager::Go2HomeRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Go2HomeRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::action_manager::Go2HomeResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Go2HomeResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<action_manager::Go2Home> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const action_manager::Go2Home&) { return value(); } 
};

template<>
struct DataType<action_manager::Go2Home> {
  static const char* value() 
  {
    return "action_manager/Go2Home";
  }

  static const char* value(const action_manager::Go2Home&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<action_manager::Go2HomeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const action_manager::Go2HomeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<action_manager::Go2HomeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_manager/Go2Home";
  }

  static const char* value(const action_manager::Go2HomeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<action_manager::Go2HomeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const action_manager::Go2HomeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<action_manager::Go2HomeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_manager/Go2Home";
  }

  static const char* value(const action_manager::Go2HomeResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_MANAGER_SERVICE_GO2HOME_H

