# DO NOT EDIT THIS FILE!
#
# Python module VnetHand generated by omniidl

import omniORB
omniORB.updateModule("VnetHand")

# ** 1. Stub files contributing to this module
import vnet3Finger_idl

# ** 2. Sub-modules

# ** 3. End
