<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hiro_base">
  <xacro:property name="base_height" value="0.900" />
  <xacro:property name="torso_height" value="0.300" />
  
  <xacro:macro name="base">
    <link name="link_base">
      <inertial>
        <origin xyz="-0.00038809 0.00000166 ${base_height+0.16466017}"/>
        <mass value="93.11081000" />
        <!-- momentsOfInertia [0.03473180 0.00000578 -0.00003341; 0.00000578 0.03474816 0.00000063; -0.00003343 0.00000062 0.00438238] -->
        <inertia  ixx="0.03473180" ixy="0.00000578"  ixz="-0.00003341"  iyy="0.03474816"  iyz="0.00000063"  izz="0.00438238" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://hiro_common/meshes/base.stl"/>
          <!--cylinder length="${base_height+torso_height}" radius="0.030"/-->
        </geometry>     
        <origin xyz="0 0 ${base_height}" rpy="0 ${-0.5*pi} ${-0.5*pi}"/>
        <!--origin xyz="0 0 ${(base_height+torso_height)/2}" rpy="0 0 0"/-->
        <material name="grey"/>
      </visual>
      <collision>
        <geometry>
          <!--mesh filename="package://hiro_common/meshes/base.stl"/-->
          <!--cylinder length="${base_height+torso_height}" radius="0.030"/-->
          <cylinder length="${torso_height}" radius="0.030"/>                
        </geometry>     
        <!--origin xyz="0 0 ${base_height}" rpy="0 ${-0.5*pi} ${-0.5*pi}"/-->
        <!--origin xyz="0 0 ${(base_height+torso_height)/2}" rpy="0 0 0"/-->
        <origin xyz="0 0 ${base_height+(torso_height/2)}" rpy="0 0 0"/> <!--This is safer because this collision model is above the table (not in collision)-->
      </collision>
    </link>	
    <gazebo reference="link_base">
      <material>Gazebo/Red</material>
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
      <turnGravityOff>true</turnGravityOff>
    </gazebo>	
  </xacro:macro>
</robot>
